[build]
  publish = "dist/web"
  command = "npm run build"
  environment = { VUE_APP_NETLIFY = "true" }

[dev]
  command = "npm run vue:serve"
  port = 3000

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  
  [[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"
